#!/bin/bash

echo "🔧 Installing SaveIt for development..."
echo ""
echo "Steps:"
echo ""
echo "1. Open Firefox Developer Edition (required for unsigned extensions)"
echo "   Download: https://www.mozilla.org/en-US/firefox/developer/"
echo ""
echo "2. Type 'about:config' in the address bar"
echo ""
echo "3. Search for: xpinstall.signatures.required"
echo ""
echo "4. Set it to: false (double-click to toggle)"
echo ""
echo "5. Go to: about:addons"
echo ""
echo "6. Click gear icon → 'Install Add-on From File'"
echo ""
echo "7. Select: extension/manifest.json"
echo ""
echo "The extension will have a permanent ID and persist across restarts!"
echo ""

