// mock-data.js - Sample saved pages for development/testing
// This data is only used when running newtab.html standalone (not in extension mode)

const MOCK_DATA = [
  {
    id: '1',
    url: 'https://example.com/motorcycling-himalayas',
    title: 'Epic Motorcycle Journey Through the Himalayas',
    description: 'A thrilling account of riding through mountain passes at 18,000 feet, crossing into forbidden territories, and experiencing the raw beauty of the highest mountains on Earth.',
    thumbnail: 'https://picsum.photos/seed/moto1/400/300',
    domain: 'example.com',
    domain_category: 'blog',
    author: 'Jane Adventure',
    published_date: '2024-01-15T10:00:00Z',
    timestamp: '2024-01-20T14:30:00Z',
    reading_time_minutes: 8,
    user_email: 'rich@airteam.com.au',
    user_name: 'Rich',
    user_notes: 'Want to plan a trip like this someday',
    manual_tags: ['travel', 'motorcycles', 'himalayas'],
    ai_summary_brief: 'A first-person account of an extreme motorcycle expedition through high-altitude Himalayan passes, exploring remote territories and documenting the challenges of high-altitude riding.',
    dewey_primary_label: 'Geography, history, related disciplines',
    ai_enriched_at: { value: '2024-01-20T15:00:00Z' }
  },
  {
    id: '2',
    url: 'https://nytimes.com/2024/01/18/technology/electric-vehicles-future',
    title: 'The Future of Electric Vehicles: What Comes Next',
    description: 'How EVs are transforming transportation, the infrastructure challenges ahead, and what the next decade holds for sustainable mobility.',
    thumbnail: 'https://picsum.photos/seed/ev1/400/300',
    domain: 'nytimes.com',
    domain_category: 'news',
    author: 'Tech Reporter',
    published_date: '2024-01-18T09:00:00Z',
    timestamp: '2024-01-20T16:45:00Z',
    reading_time_minutes: 12,
    user_email: 'rich@airteam.com.au',
    user_name: 'Rich',
    user_notes: null,
    manual_tags: ['technology', 'climate'],
    ai_summary_brief: null,
    dewey_primary_label: null,
    ai_enriched_at: null
  },
  {
    id: '3',
    url: 'https://github.com/awesome/project',
    title: 'awesome/project: A revolutionary new JavaScript framework',
    description: 'Lightweight, fast, and built for modern development. Zero dependencies, full TypeScript support, and blazing fast performance.',
    thumbnail: 'https://picsum.photos/seed/code1/400/300',
    domain: 'github.com',
    domain_category: 'code',
    author: null,
    published_date: null,
    timestamp: '2024-01-19T11:20:00Z',
    reading_time_minutes: 5,
    user_email: 'rich@airteam.com.au',
    user_name: 'Rich',
    user_notes: null,
    manual_tags: ['javascript', 'opensource'],
    ai_summary_brief: 'A minimal JavaScript framework emphasizing performance and developer experience with zero external dependencies and comprehensive TypeScript integration.',
    dewey_primary_label: 'Computer programming, programs, data',
    ai_enriched_at: { value: '2024-01-19T11:30:00Z' }
  },
  {
    id: '4',
    url: 'https://medium.com/design/principles-of-minimalist-design',
    title: 'Principles of Minimalist Design: Less is More',
    description: 'Exploring how constraints breed creativity and why the best designs often remove elements rather than add them.',
    thumbnail: 'https://picsum.photos/seed/design1/400/300',
    domain: 'medium.com',
    domain_category: 'blog',
    author: 'Design Thinker',
    published_date: '2024-01-17T14:30:00Z',
    timestamp: '2024-01-19T09:15:00Z',
    reading_time_minutes: 6,
    user_email: 'rich@airteam.com.au',
    user_name: 'Rich',
    user_notes: null,
    manual_tags: ['design', 'minimalism'],
    ai_summary_brief: null,
    dewey_primary_label: null,
    ai_enriched_at: null
  },
  {
    id: '5',
    url: 'https://arxiv.org/abs/2024.12345',
    title: 'Advances in Large Language Model Reasoning',
    description: 'A comprehensive study of chain-of-thought prompting techniques and their impact on model performance across diverse reasoning tasks.',
    thumbnail: 'https://picsum.photos/seed/paper1/400/300',
    domain: 'arxiv.org',
    domain_category: 'academic',
    author: 'Research Team',
    published_date: '2024-01-16T00:00:00Z',
    timestamp: '2024-01-18T22:10:00Z',
    reading_time_minutes: 45,
    user_email: 'rich@airteam.com.au',
    user_name: 'Rich',
    user_notes: 'Important for understanding CoT',
    manual_tags: ['ai', 'research', 'llm'],
    ai_summary_brief: 'An academic investigation into chain-of-thought prompting methods for large language models, analyzing their effectiveness across various reasoning benchmarks and task categories.',
    dewey_primary_label: 'Computer programming, programs, data',
    ai_enriched_at: { value: '2024-01-18T22:20:00Z' }
  },
  {
    id: '6',
    url: 'https://cooking.nytimes.com/recipes/perfect-sourdough',
    title: 'The Perfect Sourdough Bread Recipe',
    description: 'Master the art of sourdough with this foolproof recipe. Learn the science behind fermentation and how to achieve that perfect crust.',
    thumbnail: 'https://picsum.photos/seed/food1/400/300',
    domain: 'cooking.nytimes.com',
    domain_category: 'food',
    author: 'Chef Name',
    published_date: '2024-01-10T08:00:00Z',
    timestamp: '2024-01-18T19:30:00Z',
    reading_time_minutes: 15,
    user_email: 'rich@airteam.com.au',
    user_name: 'Rich',
    user_notes: null,
    manual_tags: ['cooking', 'bread'],
    ai_summary_brief: 'A comprehensive guide to baking artisan sourdough bread at home, covering fermentation science, starter maintenance, and techniques for achieving professional-quality crust and crumb.',
    dewey_primary_label: 'Home & family management',
    ai_enriched_at: { value: '2024-01-18T19:45:00Z' }
  },
  {
    id: '7',
    url: 'https://stackoverflow.com/questions/12345/how-to-optimize-react-performance',
    title: 'How to optimize React performance for large lists?',
    description: 'Answers covering virtualization, memoization, and other techniques for handling thousands of items efficiently.',
    thumbnail: 'https://picsum.photos/seed/code2/400/300',
    domain: 'stackoverflow.com',
    domain_category: 'code',
    author: null,
    published_date: null,
    timestamp: '2024-01-17T15:45:00Z',
    reading_time_minutes: 10,
    user_email: 'rich@airteam.com.au',
    user_name: 'Rich',
    user_notes: null,
    manual_tags: ['react', 'performance'],
    ai_summary_brief: null,
    dewey_primary_label: null,
    ai_enriched_at: null
  },
  {
    id: '8',
    url: 'https://aeon.co/essays/philosophy-of-time',
    title: 'The Philosophy of Time: Does the Past Still Exist?',
    description: 'An exploration of presentism vs eternalism and what physics tells us about the nature of temporal reality.',
    thumbnail: 'https://picsum.photos/seed/phil1/400/300',
    domain: 'aeon.co',
    domain_category: 'blog',
    author: 'Philosophy Writer',
    published_date: '2024-01-12T10:00:00Z',
    timestamp: '2024-01-17T21:00:00Z',
    reading_time_minutes: 20,
    user_email: 'rich@airteam.com.au',
    user_name: 'Rich',
    user_notes: 'Mind-bending stuff',
    manual_tags: ['philosophy', 'physics'],
    ai_summary_brief: 'A philosophical examination of temporal ontology, contrasting presentist and eternalist perspectives on time while exploring implications from modern physics and special relativity.',
    dewey_primary_label: 'Philosophy',
    ai_enriched_at: { value: '2024-01-17T21:15:00Z' }
  },
  {
    id: '9',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    title: 'Advanced TypeScript Patterns and Best Practices',
    description: 'A deep dive into conditional types, mapped types, and template literal types with real-world examples.',
    thumbnail: 'https://picsum.photos/seed/vid1/400/300',
    domain: 'youtube.com',
    domain_category: 'video',
    author: 'Code Instructor',
    published_date: '2024-01-14T12:00:00Z',
    timestamp: '2024-01-16T18:20:00Z',
    reading_time_minutes: 35,
    user_email: 'rich@airteam.com.au',
    user_name: 'Rich',
    user_notes: null,
    manual_tags: ['typescript', 'tutorial'],
    ai_summary_brief: null,
    dewey_primary_label: null,
    ai_enriched_at: null
  },
  {
    id: '10',
    url: 'https://www.theverge.com/2024/1/15/apple-vision-pro-review',
    title: 'Apple Vision Pro Review: The Future is Here (Sort Of)',
    description: 'After two weeks with Apple\'s spatial computer, here\'s what works, what doesn\'t, and whether it\'s worth $3,500.',
    thumbnail: 'https://picsum.photos/seed/tech1/400/300',
    domain: 'theverge.com',
    domain_category: 'news',
    author: 'Tech Reviewer',
    published_date: '2024-01-15T06:00:00Z',
    timestamp: '2024-01-15T20:30:00Z',
    reading_time_minutes: 18,
    user_email: 'rich@airteam.com.au',
    user_name: 'Rich',
    user_notes: null,
    manual_tags: ['apple', 'vr', 'review'],
    ai_summary_brief: 'A hands-on review of Apple Vision Pro after extended use, evaluating its spatial computing capabilities, user experience strengths and limitations, and overall value proposition at premium pricing.',
    dewey_primary_label: 'Computer science, information, works',
    ai_enriched_at: { value: '2024-01-15T20:45:00Z' }
  },
  {
    id: '11',
    url: 'https://paulgraham.com/greatwork.html',
    title: 'How to Do Great Work',
    description: 'Paul Graham\'s latest essay on finding work you love, developing taste, and the importance of curiosity.',
    thumbnail: 'https://picsum.photos/seed/essay1/400/300',
    domain: 'paulgraham.com',
    domain_category: 'blog',
    author: 'Paul Graham',
    published_date: '2024-01-08T00:00:00Z',
    timestamp: '2024-01-14T10:15:00Z',
    reading_time_minutes: 30,
    user_email: 'rich@airteam.com.au',
    user_name: 'Rich',
    user_notes: 'Re-read annually',
    manual_tags: ['career', 'philosophy'],
    ai_summary_brief: null,
    dewey_primary_label: null,
    ai_enriched_at: null
  },
  {
    id: '12',
    url: 'https://docs.anthropic.com/claude/docs/intro',
    title: 'Claude API Documentation - Getting Started',
    description: 'Learn how to integrate Claude into your applications with our comprehensive API documentation and examples.',
    thumbnail: 'https://picsum.photos/seed/docs1/400/300',
    domain: 'docs.anthropic.com',
    domain_category: 'docs',
    author: null,
    published_date: null,
    timestamp: '2024-01-13T16:40:00Z',
    reading_time_minutes: 12,
    user_email: 'rich@airteam.com.au',
    user_name: 'Rich',
    user_notes: null,
    manual_tags: ['ai', 'documentation'],
    ai_summary_brief: 'Official API documentation for integrating Claude AI assistant into applications, including setup instructions, code examples, and best practices for implementation.',
    dewey_primary_label: 'Computer programming, programs, data',
    ai_enriched_at: { value: '2024-01-13T16:50:00Z' }
  }
];
